### ISSUE TITLE
Salvar imagem no cadastro de item

### ISSUE THREAD

**Issue by mateuscardosodeveloper** [raiizoor/Web-delivery#12]
Quando é cadastrado um novo item, a imagem não é salva na pasta uploads.

**Comment by raiizoor** [comment]
O problema estava relacionado com a variavel que estaciava o formulario do FlaskForm, por algum motivo arquivos como imagem so é recebido se a variavel estiver estanciada com o nome form, exemplo:
```python
form = ItemsForm()
```

**Comment by mateuscardosodeveloper** [comment]
O problema estava relacionado com a variavel que estaciava o formulario do FlaskForm, por algum motivo arquivos como imagem so é recebido se a variavel estiver estanciada com o nome form, exemplo:
```python
form = ItemsForm()
```
Também é necessario alterar o <form> no html, exemplo.
```html
<form method='post' enctype='multipart/form-data'>
```
